Repository meta-pytorch/torch-release-notes, pull requests merged in 2025-09, with the labels that each got.

#71 2.9.0 release notes
  2.9.0/miscategorized.md
  2.9.0/todo/result_DeviceMesh.md
  2.9.0/todo/result_aotdispatcher.md
  2.9.0/todo/result_autograd_frontend.md
  2.9.0/todo/result_build_frontend.md
  2.9.0/todo/result_caffe2.md
  2.9.0/todo/result_composability.md
  2.9.0/todo/result_cpp_frontend.md
  2.9.0/todo/result_cpu (aarch64).md
  2.9.0/todo/result_cpu (x86).md
  2.9.0/todo/result_cuda.md
  2.9.0/todo/result_dataloader_frontend.md
  2.9.0/todo/result_devx.md
  2.9.0/todo/result_distributed (checkpoint).md
  2.9.0/todo/result_distributed (dtensor).md
  2.9.0/todo/result_distributed (fsdp2).md
  2.9.0/todo/result_distributed (symm_mem).md
  2.9.0/todo/result_distributed (torchelastic).md
  2.9.0/todo/result_distributed.md
  2.9.0/todo/result_dynamo.md
  2.9.0/todo/result_export.md
  2.9.0/todo/result_foreach_frontend.md
  2.9.0/todo/result_fx.md
  2.9.0/todo/result_indexing.md
  2.9.0/todo/result_inductor (aoti).md
  2.9.0/todo/result_inductor.md
  2.9.0/todo/result_jit.md
  2.9.0/todo/result_linalg_frontend.md
  2.9.0/todo/result_mobile.md
  2.9.0/todo/result_mps.md
  2.9.0/todo/result_nested tensor_frontend.md
  2.9.0/todo/result_nn_frontend.md
  2.9.0/todo/result_onnx.md
  2.9.0/todo/result_optim.md
  2.9.0/todo/result_package.md
  2.9.0/todo/result_package/deploy.md
  2.9.0/todo/result_profiler.md
  2.9.0/todo/result_python_frontend.md
  2.9.0/todo/result_quantization.md
  2.9.0/todo/result_releng.md
  2.9.0/todo/result_rocm.md
  2.9.0/todo/result_skip.md
  2.9.0/todo/result_sparse_frontend.md
  2.9.0/todo/result_vulkan.md
  2.9.0/todo/result_xpu.md
Labels: CLA Signed, module: rocm

#74 Update ONNX bc
  2.9.0/todo/result_onnx.md
Labels: CLA Signed

#78 Improve ONNX BC section
  2.9.0/todo/result_onnx.md
Labels: CLA Signed

#79 [ONNX] The rest of the notes for 2.9
  2.9.0/todo/result_onnx.md
Labels: CLA Signed

#77 Alban d patch 1
  2.9.0/done/result_linalg_frontend.md
Labels: CLA Signed

#81 Move ONNX to done
  2.9.0/done/result_onnx.md
Labels: CLA Signed

#84 composability release notes for 2.9.0
  2.9.0/done/result_composability.md
  2.9.0/miscategorized.md
Labels: CLA Signed

#86 cpp_frontend release notes for 2.9.0
  2.9.0/done/result_cpp_frontend.md
  2.9.0/miscategorized.md
Labels: CLA Signed

#87 nested tensor frontend release notes for 2.9.0
  2.9.0/todo/result_nested tensor_frontend.md
Labels: CLA Signed

#90 cpp_frontend release notes for 2.9.0
  2.9.0/done/result_cpp_frontend.md
  2.9.0/miscategorized.md
Labels: CLA Signed

#82 [ROCm] update release notes
  2.9.0/done/result_jit.md
  2.9.0/done/result_rocm.md
  2.9.0/todo/result_distributed.md
  2.9.0/todo/result_inductor.md
  2.9.0/todo/result_nn_frontend.md
  2.9.0/todo/result_quantization.md
  2.9.0/todo/result_releng.md
  2.9.0/todo/result_rocm.md
  2.9.0/todo/result_skip.md
  2.9.0/todo/result_sparse_frontend.md
Labels: CLA Signed, module: rocm

#95 export 2.9.0 release notes
  2.9.0/done/result_export.md
  2.9.0/miscategorized.md
  2.9.0/todo/result_export.md
Labels: CLA Signed

#101 move mobile into done folder
  2.9.0/done/result_mobile.md
Labels: CLA Signed

#97 Update 2.9.0 quantization release notes
  2.9.0/done/result_quantization.md
  2.9.0/miscategorized.md
Labels: CLA Signed

#100 2.9.0 release note for AOTI
  2.9.0/done/result_inductor (aoti).md
  2.9.0/miscategorized.md
  2.9.0/todo/result_inductor (aoti).md
  2.9.0/todo/result_inductor.md
Labels: CLA Signed

#103 Update dataloader release notes
  2.9.0/done/result_dataloader_frontend.md
Labels: CLA Signed

#104 nn_frontend release notes
  2.9.0/done/result_nn_frontend.md
  2.9.0/miscategorized.md
Labels: CLA Signed

#107 Autograd release notes
  2.9.0/done/result_autograd_frontend.md
  2.9.0/miscategorized.md
Labels: CLA Signed

#108 profiler update
  2.9.0/done/result_profiler.md
Labels: CLA Signed

#110 [ez] Mark Vulkan as done
  2.9.0/done/result_vulkan.md
Labels: CLA Signed, module: vulkan

#112 Initial draft for ptd release note for pt 2.9
  2.9.0/done/result_DeviceMesh.md
  2.9.0/done/result_distributed (dtensor).md
  2.9.0/done/result_distributed (fsdp2).md
  2.9.0/done/result_distributed (symm_mem).md
  2.9.0/done/result_distributed (torchelastic).md
  2.9.0/miscategorized.md
  2.9.0/todo/result_distributed.md
Labels: CLA Signed

#118 updating cherry picks
  2.9.0/done/cherrypicks.md
Labels: CLA Signed

#120 updating cherry picks
  2.9.0/done/cherrypicks.md
Labels: CLA Signed

#124 Mark distributed as done
  2.9.0/done/result_distributed.md
Labels: CLA Signed

#126 Cleanup migration notes for build_frontend
  2.9.0/todo/result_build_frontend.md
Labels: CLA Signed
